#!/usr/bin/env bash
set -euo pipefail

PI_USER="${PI_USER:-pi}"
PI_HOST="${PI_HOST:-192.168.1.52}"
PI_DIR="${PI_DIR:-~/cafeqr}"
BASE_PATH="${BASE_PATH:-/}"
BACKEND_IMAGE="${BACKEND_IMAGE:-cafeqr-backend:deploy}"
RUN_SEED="${RUN_SEED:-false}"
ROOT="$(cd "$(dirname "$0")" && pwd)"
BUILD_DIR="$(mktemp -d "${TMPDIR:-/tmp}/cafeqr-deploy.XXXXXX")"
IMAGE_ARCHIVE="$BUILD_DIR/backend-image.tar.gz"
trap 'rm -rf "$BUILD_DIR"' EXIT

echo "==> Building frontend with base: $BASE_PATH"
cd "$ROOT/frontend-react"
VITE_BASE_PATH="$BASE_PATH" npm run build

echo ""
echo "==> Building ARM64 backend image locally: $BACKEND_IMAGE"
docker build --platform linux/arm64 -t "$BACKEND_IMAGE" "$ROOT"

echo ""
echo "==> Packing backend image for transfer"
docker save "$BACKEND_IMAGE" | gzip -1 > "$IMAGE_ARCHIVE"

echo ""
echo "==> Generating .env from local environment"
APP_JWT_SECRET_VALUE="${APP_JWT_SECRET:-}"
if [ -z "$APP_JWT_SECRET_VALUE" ] && [ -f "$ROOT/.env" ]; then
  APP_JWT_SECRET_VALUE="$(grep -E '^APP_JWT_SECRET=' "$ROOT/.env" | head -n1 | cut -d= -f2- || true)"
fi
if [ -z "$APP_JWT_SECRET_VALUE" ]; then
  APP_JWT_SECRET_VALUE="$(openssl rand -base64 48)"
fi
POSTGRES_PASSWORD_VALUE="${POSTGRES_PASSWORD:-}"
if [ -z "$POSTGRES_PASSWORD_VALUE" ] && [ -f "$ROOT/.env" ]; then
  POSTGRES_PASSWORD_VALUE="$(grep -E '^POSTGRES_PASSWORD=' "$ROOT/.env" | head -n1 | cut -d= -f2- || true)"
fi
if [ -z "$POSTGRES_PASSWORD_VALUE" ]; then
  POSTGRES_PASSWORD_VALUE="$(openssl rand -base64 24 | tr -dc 'A-Za-z0-9')"
fi
cat > "$ROOT/.env" <<EOF
# Auto-generated by deploy.sh — set your real values below
POSTGRES_PASSWORD=${POSTGRES_PASSWORD_VALUE}
BREVO_SMTP_HOST=${BREVO_SMTP_HOST:-smtp-relay.brevo.com}
BREVO_SMTP_LOGIN=${BREVO_SMTP_LOGIN:-}
BREVO_SMTP_KEY=${BREVO_SMTP_KEY:-}
APP_JWT_SECRET=${APP_JWT_SECRET_VALUE}
APP_EMAIL_PROVIDER=${APP_EMAIL_PROVIDER:-smtp}
APP_EMAIL_FROM=${APP_EMAIL_FROM:-Serva <onboarding@example.com>}
APP_ADMIN_ALERT_EMAIL=${APP_ADMIN_ALERT_EMAIL:-}
APP_BILLING_PLAN=${APP_BILLING_PLAN:-Annual}
APP_BILLING_PRICE=${APP_BILLING_PRICE:-29.000}
APP_BILLING_CURRENCY=${APP_BILLING_CURRENCY:-OMR}
APP_BILLING_BANK_NAME=${APP_BILLING_BANK_NAME:-CHANGE_ME}
APP_BILLING_ACCOUNT_NAME=${APP_BILLING_ACCOUNT_NAME:-CHANGE_ME}
APP_BILLING_ACCOUNT_NUMBER=${APP_BILLING_ACCOUNT_NUMBER:-CHANGE_ME}
APP_BILLING_IBAN=${APP_BILLING_IBAN:-CHANGE_ME}
EOF

echo ""
echo "==> Syncing deployment artifacts to $PI_USER@$PI_HOST:$PI_DIR"
ssh "$PI_USER@$PI_HOST" "mkdir -p $PI_DIR/frontend-react/dist"
rsync -avz --delete "$ROOT/frontend-react/dist/" \
  "$PI_USER@$PI_HOST:$PI_DIR/frontend-react/dist/"
rsync -avz "$ROOT/docker-compose.yml" "$ROOT/.env" \
  "$PI_USER@$PI_HOST:$PI_DIR/"
rsync -avz "$IMAGE_ARCHIVE" \
  "$PI_USER@$PI_HOST:$PI_DIR/backend-image.tar.gz"

echo ""
echo "==> Fixing permissions for nginx read access"
ssh "$PI_USER@$PI_HOST" "sudo chmod -R a+rX $PI_DIR/frontend-react/dist/ && sudo chmod a+X /home/$PI_USER"

echo ""
echo "==> Uploading nginx gzip tuning"
ssh "$PI_USER@$PI_HOST" "sudo tee /etc/nginx/conf.d/cafeqr-gzip.conf > /dev/null" <<'GZIP'
# Compress JSON/JS/CSS leaving the Pi. Cloudflare re-compresses to visitors, but
# without this the origin->edge hop crosses the tunnel uncompressed.
# text/event-stream is deliberately absent: SSE must never be gzip-buffered.
gzip_vary on;
gzip_proxied any;
gzip_comp_level 5;
gzip_min_length 512;
gzip_types text/plain text/css application/json application/javascript text/javascript image/svg+xml application/manifest+json;
GZIP

echo ""
echo "==> Uploading nginx config for $BASE_PATH"
ssh "$PI_USER@$PI_HOST" "sudo tee /etc/nginx/snippets/cafeqr-paths.conf > /dev/null" <<'NGINX'
# Serva / CafeQR reverse proxy paths

# API backend
location /api/ {
    proxy_pass http://127.0.0.1:8080/api/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    client_max_body_size 50M;
}

# File uploads — filenames are UUIDs, so a URL's content never changes; cache hard.
# (Matches the Cache-Control the backend itself sends; hide avoids double headers.)
location /files/ {
    proxy_pass http://127.0.0.1:8080/files/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_hide_header Cache-Control;
    add_header Cache-Control "public, max-age=31536000, immutable";
    client_max_body_size 50M;
}

# SPA — Admin & Dashboard (built with base /serva)
location /serva {
    alias /home/pi/cafeqr/frontend-react/dist;
    try_files $uri $uri/ /serva/index.html;
    location ~ ^/serva/assets/ {
        add_header Cache-Control "public, max-age=31536000, immutable";
    }
}

# SPA — Customer-facing routes (menu, cart, order tracking)
location /r/ {
    rewrite ^ /serva/index.html last;
}
location /cart {
    rewrite ^ /serva/index.html last;
}
location /order/ {
    rewrite ^ /serva/index.html last;
}
location /admin {
    rewrite ^ /serva/index.html last;
}
location /dashboard {
    rewrite ^ /serva/index.html last;
}
NGINX

echo ""
echo "==> Adding include to nginx default site (if missing)"
ssh "$PI_USER@$PI_HOST" "grep -q 'cafeqr-paths' /etc/nginx/sites-enabled/default || sudo sed -i '/include snippets\/law-stack-paths.conf;/a\    include snippets/cafeqr-paths.conf;' /etc/nginx/sites-enabled/default"

echo ""
echo "==> Uploading nginx server block for serva.om"
ssh "$PI_USER@$PI_HOST" "sudo tee /etc/nginx/sites-available/serva.om > /dev/null" <<'SERVA'
server {
    listen 80;
    listen [::]:80;
    server_name serva.om www.serva.om;

    set_real_ip_from 103.21.244.0/22;
    set_real_ip_from 103.22.200.0/22;
    set_real_ip_from 103.31.4.0/22;
    set_real_ip_from 104.16.0.0/13;
    set_real_ip_from 104.24.0.0/14;
    set_real_ip_from 108.162.192.0/18;
    set_real_ip_from 131.0.72.0/22;
    set_real_ip_from 141.101.64.0/18;
    set_real_ip_from 162.158.0.0/15;
    set_real_ip_from 172.64.0.0/13;
    set_real_ip_from 173.245.48.0/20;
    set_real_ip_from 188.114.96.0/20;
    set_real_ip_from 190.93.240.0/20;
    set_real_ip_from 197.234.240.0/22;
    set_real_ip_from 198.41.128.0/17;
    real_ip_header CF-Connecting-IP;

    location /api/ {
        proxy_pass http://127.0.0.1:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        client_max_body_size 50M;
    }

    location /files/ {
        proxy_pass http://127.0.0.1:8080/files/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_hide_header Cache-Control;
        add_header Cache-Control "public, max-age=31536000, immutable";
        client_max_body_size 50M;
    }

    # The SPA shell must never be cached: hashed asset URLs live inside it, so a stale
    # index.html pins tablets to an old bundle for days after a deploy.
    location = /index.html {
        root /home/pi/cafeqr/frontend-react/dist;
        add_header Cache-Control "no-cache, must-revalidate";
    }

    location / {
        root /home/pi/cafeqr/frontend-react/dist;
        try_files $uri $uri/ /index.html;
        location ~ ^/assets/ {
            add_header Cache-Control "public, max-age=31536000, immutable";
        }
    }
}
SERVA
ssh "$PI_USER@$PI_HOST" "sudo ln -sf /etc/nginx/sites-available/serva.om /etc/nginx/sites-enabled/serva.om"

echo ""
echo "==> Testing nginx config"
ssh "$PI_USER@$PI_HOST" "sudo nginx -t"

echo ""
echo "==> Reloading nginx"
ssh "$PI_USER@$PI_HOST" "sudo systemctl reload nginx"

echo ""
echo "==> Loading locally built backend image and restarting containers"
ssh "$PI_USER@$PI_HOST" \
  "cd $PI_DIR && gzip -dc backend-image.tar.gz | docker load && rm -f backend-image.tar.gz && docker compose up -d --no-build"

echo ""
echo "==> Waiting for backend health..."
sleep 10
healthy=false
for i in $(seq 1 12); do
  status=$(ssh "$PI_USER@$PI_HOST" "curl -s -o /dev/null -w '%{http_code}' http://localhost:8080/actuator/health" 2>/dev/null || true)
  if [ "$status" = "200" ]; then
    echo "Backend is UP (HTTP 200)"
    healthy=true
    break
  fi
  echo "  attempt $i/12 — waiting..."
  sleep 5
done
if [ "$healthy" != "true" ]; then
  echo "Backend failed its health check; recent logs:" >&2
  ssh "$PI_USER@$PI_HOST" "cd $PI_DIR && docker compose logs --tail=100 backend" >&2 || true
  exit 1
fi

echo ""
echo "==> Removing superseded images and obsolete build cache"
# Run cleanup only after the replacement backend is healthy. Deliberately avoid
# system/volume pruning: database and upload volumes must never be touched.
ssh "$PI_USER@$PI_HOST" "docker image prune -f && docker builder prune -af"

if [ "$RUN_SEED" = "true" ]; then
  echo ""
  echo "==> Seeding demo data..."
  cd "$ROOT/frontend-react"
  API_BASE="http://$PI_HOST:8080" node scripts/seed.mjs
fi

echo ""
echo "==> Done! Deployed at https://serva.om (and https://m7m2od.com/serva)"
