#!/usr/bin/env bash
set -euo pipefail

PI_USER="${PI_USER:-pi}"
PI_HOST="${PI_HOST:-192.168.1.52}"
PI_DIR="${PI_DIR:-~/cafeqr}"
BASE_PATH="${BASE_PATH:-/}"
ROOT="$(cd "$(dirname "$0")" && pwd)"

echo "==> Building frontend with base: $BASE_PATH"
cd "$ROOT/frontend-react"
VITE_BASE_PATH="$BASE_PATH" npm run build

echo ""
echo "==> Generating .env from local environment"
APP_JWT_SECRET_VALUE="${APP_JWT_SECRET:-}"
if [ -z "$APP_JWT_SECRET_VALUE" ] && [ -f "$ROOT/.env" ]; then
  APP_JWT_SECRET_VALUE="$(grep -E '^APP_JWT_SECRET=' "$ROOT/.env" | head -n1 | cut -d= -f2- || true)"
fi
if [ -z "$APP_JWT_SECRET_VALUE" ]; then
  APP_JWT_SECRET_VALUE="$(openssl rand -base64 48)"
fi
cat > "$ROOT/.env" <<EOF
# Auto-generated by deploy.sh — set your real values below
BREVO_SMTP_HOST=${BREVO_SMTP_HOST:-smtp-relay.brevo.com}
BREVO_SMTP_LOGIN=${BREVO_SMTP_LOGIN:-}
BREVO_SMTP_KEY=${BREVO_SMTP_KEY:-}
APP_JWT_SECRET=${APP_JWT_SECRET_VALUE}
APP_EMAIL_PROVIDER=${APP_EMAIL_PROVIDER:-smtp}
APP_EMAIL_FROM=${APP_EMAIL_FROM:-Serva <onboarding@example.com>}
APP_ADMIN_ALERT_EMAIL=${APP_ADMIN_ALERT_EMAIL:-}
APP_ONBOARDING_PLAN=${APP_ONBOARDING_PLAN:-Annual}
APP_ONBOARDING_PRICE=${APP_ONBOARDING_PRICE:-29.000}
APP_ONBOARDING_CURRENCY=${APP_ONBOARDING_CURRENCY:-OMR}
APP_ONBOARDING_BANK_NAME=${APP_ONBOARDING_BANK_NAME:-CHANGE_ME}
APP_ONBOARDING_ACCOUNT_NAME=${APP_ONBOARDING_ACCOUNT_NAME:-CHANGE_ME}
APP_ONBOARDING_ACCOUNT_NUMBER=${APP_ONBOARDING_ACCOUNT_NUMBER:-CHANGE_ME}
APP_ONBOARDING_IBAN=${APP_ONBOARDING_IBAN:-CHANGE_ME}
EOF

echo ""
echo "==> Syncing project to $PI_USER@$PI_HOST:$PI_DIR"
rsync -avz --delete \
  --exclude '.git' \
  --exclude 'docker-compose.override.yml' \
  --exclude 'target/' \
  --exclude '.DS_Store' \
  --exclude '.claude/' \
  --exclude 'node_modules/' \
  --exclude 'frontend-react/node_modules/' \
  --exclude 'frontend-react/src/' \
  ../ pi@192.168.1.52:~/cafeqr/

echo ""
echo "==> Fixing permissions for nginx read access"
ssh "$PI_USER@$PI_HOST" "sudo chmod -R a+rX $PI_DIR/frontend-react/dist/ && sudo chmod a+X /home/$PI_USER"

echo ""
echo "==> Uploading nginx gzip tuning"
ssh "$PI_USER@$PI_HOST" "sudo tee /etc/nginx/conf.d/cafeqr-gzip.conf > /dev/null" <<'GZIP'
# Compress JSON/JS/CSS leaving the Pi. Cloudflare re-compresses to visitors, but
# without this the origin->edge hop crosses the tunnel uncompressed.
# text/event-stream is deliberately absent: SSE must never be gzip-buffered.
gzip_vary on;
gzip_proxied any;
gzip_comp_level 5;
gzip_min_length 512;
gzip_types text/plain text/css application/json application/javascript text/javascript image/svg+xml application/manifest+json;
GZIP

echo ""
echo "==> Uploading nginx config for $BASE_PATH"
ssh "$PI_USER@$PI_HOST" "sudo tee /etc/nginx/snippets/cafeqr-paths.conf > /dev/null" <<'NGINX'
# Serva / CafeQR reverse proxy paths

# API backend
location /api/ {
    proxy_pass http://127.0.0.1:8080/api/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    client_max_body_size 50M;
}

# File uploads — filenames are UUIDs, so a URL's content never changes; cache hard.
# (Matches the Cache-Control the backend itself sends; hide avoids double headers.)
location /files/ {
    proxy_pass http://127.0.0.1:8080/files/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_hide_header Cache-Control;
    add_header Cache-Control "public, max-age=31536000, immutable";
    client_max_body_size 50M;
}

# SPA — Admin & Dashboard (built with base /serva)
location /serva {
    alias /home/pi/cafeqr/frontend-react/dist;
    try_files $uri $uri/ /serva/index.html;
    location ~ ^/serva/assets/ {
        add_header Cache-Control "public, max-age=31536000, immutable";
    }
}

# SPA — Customer-facing routes (menu, cart, order tracking)
location /r/ {
    rewrite ^ /serva/index.html last;
}
location /cart {
    rewrite ^ /serva/index.html last;
}
location /order/ {
    rewrite ^ /serva/index.html last;
}
location /admin {
    rewrite ^ /serva/index.html last;
}
location /dashboard {
    rewrite ^ /serva/index.html last;
}
NGINX

echo ""
echo "==> Adding include to nginx default site (if missing)"
ssh "$PI_USER@$PI_HOST" "grep -q 'cafeqr-paths' /etc/nginx/sites-enabled/default || sudo sed -i '/include snippets\/law-stack-paths.conf;/a\    include snippets/cafeqr-paths.conf;' /etc/nginx/sites-enabled/default"

echo ""
echo "==> Uploading nginx server block for serva.om"
ssh "$PI_USER@$PI_HOST" "sudo tee /etc/nginx/sites-available/serva.om > /dev/null" <<'SERVA'
server {
    listen 80;
    listen [::]:80;
    server_name serva.om www.serva.om;

    set_real_ip_from 103.21.244.0/22;
    set_real_ip_from 103.22.200.0/22;
    set_real_ip_from 103.31.4.0/22;
    set_real_ip_from 104.16.0.0/13;
    set_real_ip_from 104.24.0.0/14;
    set_real_ip_from 108.162.192.0/18;
    set_real_ip_from 131.0.72.0/22;
    set_real_ip_from 141.101.64.0/18;
    set_real_ip_from 162.158.0.0/15;
    set_real_ip_from 172.64.0.0/13;
    set_real_ip_from 173.245.48.0/20;
    set_real_ip_from 188.114.96.0/20;
    set_real_ip_from 190.93.240.0/20;
    set_real_ip_from 197.234.240.0/22;
    set_real_ip_from 198.41.128.0/17;
    real_ip_header CF-Connecting-IP;

    location /api/ {
        proxy_pass http://127.0.0.1:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        client_max_body_size 50M;
    }

    location /files/ {
        proxy_pass http://127.0.0.1:8080/files/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_hide_header Cache-Control;
        add_header Cache-Control "public, max-age=31536000, immutable";
        client_max_body_size 50M;
    }

    location / {
        root /home/pi/cafeqr/frontend-react/dist;
        try_files $uri $uri/ /index.html;
        location ~ ^/assets/ {
            add_header Cache-Control "public, max-age=31536000, immutable";
        }
    }
}
SERVA
ssh "$PI_USER@$PI_HOST" "sudo ln -sf /etc/nginx/sites-available/serva.om /etc/nginx/sites-enabled/serva.om"

echo ""
echo "==> Testing nginx config"
ssh "$PI_USER@$PI_HOST" "sudo nginx -t"

echo ""
echo "==> Reloading nginx"
ssh "$PI_USER@$PI_HOST" "sudo systemctl reload nginx"

echo ""
echo "==> Rebuilding and restarting Docker containers"
ssh "$PI_USER@$PI_HOST" "cd $PI_DIR && docker compose up -d --build"

echo ""
echo "==> Waiting for backend health..."
sleep 10
for i in $(seq 1 12); do
  status=$(ssh "$PI_USER@$PI_HOST" "curl -s -o /dev/null -w '%{http_code}' http://localhost:8080/actuator/health" 2>/dev/null || true)
  if [ "$status" = "200" ]; then
    echo "Backend is UP (HTTP 200)"
    break
  fi
  echo "  attempt $i/12 — waiting..."
  sleep 5
done

echo ""
echo "==> Seeding demo data..."
cd "$ROOT/frontend-react"
API_BASE="http://$PI_HOST:8080" node scripts/seed.mjs

echo ""
echo "==> Done! Deployed at https://serva.om (and https://m7m2od.com/serva)"
