-- =====================================================================
-- Returning-customer support.
--
-- customer_profiles: one row per (restaurant, device). The device token is a
-- random UUID generated by the customer's browser and stored in localStorage;
-- it is the credential for reading the profile back (never enumerable by
-- phone). Phone stays unverified until OTP opt-in lands.
--
-- blocked_phones: per-restaurant blocklist for fake/spam orders. Order
-- creation rejects orders whose normalized phone matches.
-- =====================================================================

CREATE TABLE customer_profiles (
    id             BIGSERIAL    PRIMARY KEY,
    restaurant_id  BIGINT       NOT NULL REFERENCES restaurants (id),
    device_token   VARCHAR(64)  NOT NULL,
    customer_name  VARCHAR(150),
    customer_phone VARCHAR(40),
    car_plate      VARCHAR(40),
    car_color      VARCHAR(20),
    order_count    INT          NOT NULL DEFAULT 0,
    last_order_at  TIMESTAMPTZ,
    created_at     TIMESTAMPTZ  NOT NULL,
    updated_at     TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_customer_profiles_device UNIQUE (restaurant_id, device_token)
);

CREATE TABLE blocked_phones (
    id            BIGSERIAL    PRIMARY KEY,
    restaurant_id BIGINT       NOT NULL REFERENCES restaurants (id),
    phone         VARCHAR(40)  NOT NULL,
    reason        VARCHAR(300),
    blocked_by    VARCHAR(150),
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_blocked_phones UNIQUE (restaurant_id, phone)
);

-- Favorite-order scoring scans a single customer's history.
CREATE INDEX idx_orders_restaurant_phone
    ON orders (restaurant_id, customer_phone)
    WHERE customer_phone IS NOT NULL;
